
services:
  test_db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_meal_log_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_meal_log_db -h localhost -p 5432"]
      interval: 1s
      timeout: 5s
      retries: 30
