ALTER TABLE meal_logs
  ADD COLUMN IF NOT EXISTS dish TEXT,
  ADD COLUMN IF NOT EXISTS confidence REAL,
  ADD COLUMN IF NOT EXISTS ai_raw JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS user_overrides JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'ai',
  ADD COLUMN IF NOT EXISTS version INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS protein_g NUMERIC,
  ADD COLUMN IF NOT EXISTS fat_g NUMERIC,
  ADD COLUMN IF NOT EXISTS carbs_g NUMERIC,
  ADD COLUMN IF NOT EXISTS calories NUMERIC;
