name: ci-test

on: [push, pull_request]

jobs:
  test:
    name: ci-test-job
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      ENABLE_CRON: false
      DATABASE_URL: postgresql://test_user:test_password@test_db:5432/test_meal_log_db

    services:
      test_db:
        image: postgres:13
        ports: ['5433:5432']
        env:
          POSTGRES_DB: test_meal_log_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Drop and Recreate Test DB
        run: |
          psql -h test_db -U test_user -d postgres -c "DROP DATABASE IF EXISTS test_meal_log_db;"
          psql -h test_db -U test_user -d postgres -c "CREATE DATABASE test_meal_log_db;"
        env:
          PGPASSWORD: test_password

      - name: Install deps (CI)
        run: npm ci

      - name: Run Migrations
        run: npm run migrate:reset

      - name: Lint
        run: npx eslint . --max-warnings=0

      - name: Test
        run: npm test --if-present
