name: ci-test

on: [push, pull_request]

jobs:
  test:
    name: ci-test-job
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      ENABLE_CRON: false
      DATABASE_URL: postgresql://test_user:test_password@localhost:5433/test_meal_log_db

    services:
      test_db:
        image: postgres:13
        ports: ['5433:5432']
        env:
          POSTGRES_DB: test_meal_log_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5433 -U test_user -d test_meal_log_db; do
            echo "Waiting for database..."
            sleep 2
          done
        env:
          PGPASSWORD: test_password

      - name: Install deps (CI)
        run: npm ci

      - name: Run Migrations
        run: npm run migrate:latest -- --env test # テスト環境のknex設定を使用

      - name: Lint
        run: npx eslint . --max-warnings=0

      - name: Test
        run: npm test --if-present
